### PR TITLE
Fix medistation animation

### LINKED ISSUE #1409: medistation effect blinds the user
It was suggested to me by a player, than the medistation animation blinds the user too much.

### PR DESCRIPTION
**Pull request by VReaperV**
Replaces the horrible blocking medistation animation with rings that blend slightly more as well. Fixes https://github.com/Unvanquished/Unvanquished/issues/1409.

unvanquished_2024-02-07_133003_000
unvanquished_2024-02-07_133142_000
unvanquished_2024-02-07_133210_000

### CODE REVIEW

**Comment by VReaperV** [comment]
The second and third screenshot didn't capture them proprely for whatever reason, but they look proper in-game.

**Comment by sweet235** [comment]
I like this already. I'll try to test it today.

**Comment by cu-kai** [comment]
Having tested this ingame, I really like this change. LGTM.

**Comment by sweet235** [comment]
LGTM

**Pull request merged**
