### PR TITLE
arm: Add a display texture to the arm

### PR DESCRIPTION
**Pull request by DolceTriade**
Currently, the arm has no display texture on the screen so it just looks grey and bland. This adds a texture and a noise/overscan effect similar to the ckit.

Sources:
UI:
https://opengameart.org/content/sci-fi-interface-textures
author: https://opengameart.org/users/rubberduck

Cracked screen:
https://www.deviantart.com/everythingisinstock/art/Cracked-Glass-Texture-III-118381859
author: https://www.deviantart.com/everythingisinstock

We'll need to add them to the thank you in the credits.

Screenshots:
Alive:

Dead:

### CODE REVIEW

**Comment by illwieckz** [comment]
I added a commit (to be squashed before merging!) that recompresses the data to save space.

Before:

```
$ du -shc screen.png screen_off.png screen.xcf scroll.png scroll.xcf
340K	screen.png
656K	screen_off.png
3,1M	screen.xcf
336K	scroll.png
1,5M	scroll.xcf
5,8M	total
```

After:

```
$ du -shc screen.webp screen_off.webp screen.xcf.xz scroll.webp scroll.xcf.xz
68K	screen.webp
428K	screen_off.webp
980K	screen.xcf.xz
220K	scroll.webp
260K	scroll.xcf.xz
2,0M	total
```

Here are the commands:

```
xz -9 file.xcf
cwebp -v -mt -lossless -exact -z 9 file.png -o file.webp
```

GIMP can open `file.xcf.xz` without extra work, it can also save directly to `file.xcf.xz` by typing the `file.xcf.xz` name in save dialog. I don't know what is the default compression level used by GIMP though.

GIMP can also export to WebP directly, but I don't know if it uses the `-exact` option (needed to also keep alpha channel lossless when it exists) and what is the default compression level.

**Comment by illwieckz** [comment]
We may want to make the screen glow to avoid this difference of looking:

unvanquished_2024-04-30_021956_000

unvanquished_2024-04-30_021959_000

**Comment by illwieckz** [comment]
I added a fixup commit to squash as well, making the screen glow when alive:

unvanquished_2024-04-30_023210_000

unvanquished_2024-04-30_023310_000

I removed the `specularMap` line when the screen is alive, because for now there is no way to render dynamic lights if lightmaps are not applied anyway. The same happens with glowMaps: they are always above all the lights. Here the entire screen glows so we can use a basic stage. To get the same result, one can set the texture as a glowMap over a black diffuse, but it will run more complex C++ and GLSL code for the exact same result.

**Comment by DolceTriade** [comment]
Cool, LGTM!

**Comment by illwieckz** [comment]
I made it looking different when off and when destroyed, because it is weird to see a cracked screen when the reactor is down. I reused the previous screen texture for that.

Alive:

unvanquished_2024-04-30_041530_000

Unpowered:

unvanquished_2024-04-30_041602_000

Dead:

unvanquished_2024-04-30_041644_000

**Comment by illwieckz** [comment]
Well, maybe it is weird that the dead screen is blue if the unpowered one isn't blue. On the other hand while being destroyed it is not unpowered and things may behave differently (one may even display a blue screen of death 😅️).

So, either we unify the colour for both off and dead (maybe gray?), either we make the dead screen difference even more obvious in a way there is no doubt it is intentionnal, actually a blue screen of death would be fun!

**Comment by illwieckz** [comment]
Can be fun: https://en.wikipedia.org/wiki/File:Windows_9X_BSOD.png

Windows 9X BSOD

**Comment by DolceTriade** [comment]
Sure, I figured we can iteratively improve this.

**Comment by illwieckz** [comment]
OK, let's consider this is good enough then, all the layout is there, we can improve the textures later.

**Comment by DolceTriade** [comment]
Safe to merge?

**Comment by illwieckz** [comment]
Yes.

**Pull request merged**
